# Configurations for AutoSync Hub

# Secret Token
SECRET_TOKEN: d6b7102b2fd1d510fd9fa44343e2a24c2b6a303e01288b47689acab522dd5a5d

PORT: 5000

REPOSITORIES:
  - timer-app: /root/Desktop/timer-app
  - lab_scheduler: /root/lab-scheduler
